config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories
  resources :articles
  
  get 'main/index'
  root "profiles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 255 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  # associations
  has_many :articles, dependent: :destroy
  belongs_to :user
  
  # validations
  validates :name, presence: true, length: { maximum: 255 }
  validates :color, presence: true
  validates :user, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # associations
  belongs_to :user
  
  # validations
  validates :firstname, presence: true, length: { maximum: 255 }
  validates :lastname, presence: true, length: { maximum: 255 }
  
  def self.search(search)
    if search
      where('firstname LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  # associations
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  
  has_many :categories, dependent: :destroy
  
  # validations
  validates :profile, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "profile_layout", only: [:show]
  before_action :authenticate_user!, :except => [:show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    if (params[:categories]) then
      @articles = Article.where(published: true, category_id: params[:categories])
    else 
      @articles = Article.where(published: true, category_id: current_user.categories.pluck(:id))
    end
    
    @categories = Article.where(published: true, category_id: current_user.categories.pluck(:id)).map(&:category).compact.uniq
  end

  def show
    @profile = @article.category.user.profile
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name, :caption, :content, :published, :thumbnail, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new(user_id: current_user.id)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to articles_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color, :user_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @profiles = Profile.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "profile_layout", only: [:show]
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.search(params[:search]).paginate(per_page: 5, page: params[:page])
  end

  def show
    @categories = Article.where(published: true, category_id: @profile.user.categories.pluck(:id)).map(&:category).compact.uniq
    @articles = Article.where(published: true, category_id: @categories.map(&:id)) unless params[:categories]
    @articles = Article.where(published: true, category_id: params[:categories]) if params[:categories]
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :profile_picture, :banner_picture, :bio, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 def new
   build_resource({})
   resource.build_profile 
   respond_with self.resource
 end
 
 private
 
  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
    params.require(:user).permit(:email, :password, profile_attributes: [:firstname, :lastname, :bio, :profile_picture])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/articles/_article.html.erb
<div class="box">
  <div class="card" align="center" style="border-color:<%= article.category.color %>;">
    <a href=<%= article_path(article) %>>
      <img class="card-img-top img-rounded" src=<%= article.thumbnail %> alt=<%= t("errors.image_not_found") %>>
      <div class="card-block">
        <h4 class="card-title"><%= article.name %></h4>
        <p class="card-text text-muted"><%= article.caption %></p>
      </div>
      <div class="card-footer text-muted">
        <%= distance_of_time_in_words(article.created_at, Time.zone.now) %> ago
      </div>
    </a>
  </div>
</div>

app/views/articles/_article_nav.html.erb
<div id="navbar-article" class="white-card">
  <ul class="nav nav-pills nav-stacked"></ul>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article, wrapper: :horizontal_form, validate: true, html: { class: 'form-horizontal' }) do |f| %>
  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 .col-lg-offset-4 col-md-offset-4">
    <%= f.input :name %>
    <%= f.input :thumbnail %>
    <%= f.input :caption %>
    <%= f.association :category, collection: current_user.categories.all, label_method: :name, value_method: :id, include_blank: false %>
  </div>
  <div class="col-xs-12">
    <%= f.text_area :content, class: "tinymce", rows: 40, cols: 120 %>
    <%= tinymce %>
  </div>
  
  <div align="center" class="col-lg-4 col-md-4 col-sm-12 col-xs-12 .col-lg-offset-4 col-md-offset-4">
    <%= f.input :published %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div id="articles-background">
  iqsjfksjqdkfm
  <div id="articles" class="transitions-enabled">
    <% @articles.each do |article| %>
      <%= render partial: "article", locals: { article: article } %>
    <% end %>
  </div>
</div>

app/views/articles/index.js.erb
$('#articles').html("<%= escape_javascript render(@articles) %>");
$('#articles').masonry('reload');

app/views/articles/new.html.erb
<h1 align="center"><%= t("article.new_article") %> </h1>

<div align="center">
  <%= link_to 'Back', :back %>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_article_path(@article) %>
  <% end %>
  <div id="article-content">
    <%= raw @article.content %>
  </div>
</div>
<div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
  <%= render partial: "articles/article_nav" %>
</div>

app/views/categories/_categories.html.erb
<div id="categories" class="white-card">
  <div align="center">
    <h4><%= t("category.categories") %></h4>
    <% if @profile.user == current_user %>
      <%= link_to 'New Category', new_category_path %>
    <% end %>
  </div>
  <hr class="m-y-2">
  <fieldset id="category_filters">
    <% categories.each do |category| %>
      <%= check_box_tag("category_filter_#{category.id}", category.id) %>
      <b style="color:<%= category.color %>"><%= category.name %></b>
      <br>
    <% end %>
  </fieldset>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category, wrapper: :horizontal_form, validate: true, html: { class: 'form-horizontal' }) do |f| %>
  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 .col-lg-offset-4 col-md-offset-4">
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :name %>
    <%= f.input :color, as: :minicolors, input_html: {data: {
          minicolors: {theme: :bootstrap, position: :left}}} %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div align="center">
  <h1>New Category</h1>
  <%= link_to 'Back', :back %>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_footer.html.erb
<nav class="navbar-fluid navbar-light bg-faded">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <p id="copyright" class="navbar-text">Copyright © <%= Time.now.year %> - <%= t("name") %></p>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<div id="header" style="background-color: blue">
  <div class="container-fluid">
    <div class="row">
      <div id="header-content" class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
        <img id="profile-image" class="img-thumbnail" src="https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/13001232_10204567135937028_2527015623866539451_n.jpg?oh=de18edd1cbc7772669e46a9b66ef9e59&oe=58100C96" alt=<%= t("not_found") %>></img>
      </div>
    </div>
  </div>
</div>
<div id="profile-nav">
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link active" href="#">Active</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Disabled</a>
    </li>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav id="navbar" class="navbar navbar-fixed-top navbar-light">
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= main_index_path %>"><%= t("nav.startpage") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= t("nav.notifications") %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= t("nav.messages") %></a>
      </li>
      <form class="form-inline pull-xs-right">
        <li class="nav-item dropdown">
          <a id="navbar-profile-picture" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <img class="img-rounded" src=<%= current_user.profile.profile_picture %> />
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="<%= profile_path(current_user.profile) %>"><%= t("profile.go_to_profile") %></a>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>"><%= t("authentication.edit_account") %></a>
            <div class="dropdown-divider"></div>
            <%= link_to(t("authentication.sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item") %>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_article_path %>"><%= t("article.new_article") %></a>
        </li>
      </form>
    </ul>
  </nav>
<% end %>
       

app/views/layouts/_profile_navbar.html.erb
<nav id="profile-navbar" class="navbar navbar-light">
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a id="profile-navbar-picture" class="nav-link" href="#">
        <img class="img-thumbnail" src=<%= @profile.profile_picture %> />  
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Articles</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Subscriped</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Subscripers</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("name") %></title>
    <!--correct scaling on smartphones-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div id="wrap">
      <div id="content" class="container-fluid">
        <%= flash_messages %>
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/profile_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("name") %></title>
    <!--correct scaling on smartphones-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div id="header" style="background-image: url(<%= @profile.banner_picture %>)"></div>
    <%= render "layouts/profile_navbar" %>
    <div id="wrap">
        <div id="content">
          <div class="row">
            <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1">
              <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
                <%= render partial: "profiles/bio", locals: { profile: @profile } %>
              </div>
              <%= yield %>
            </div>
          </div>
        </div>
    </div>
    <div id="footer">
      <%= render "layouts/footer" %>
    </div>
    
    <%= javascript_include_tag 'lightbox', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/main/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
      <%= render "_table" %>
    </div>
  </div>
</div>

app/views/profiles/_bio.html.erb
<div id="bio" class="white-card">
  <div align="center">
    <h4><%= "#{ profile.firstname } #{ profile.lastname }" %></h4>
    <% if profile.user == current_user %>
      <%= link_to t("basic.edit"), edit_profile_path(profile) %>
    <% end %>
  </div>
  <hr class="m-y-2">
  <p> <%= profile.bio %> </p>
</div>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile, wrapper: :horizontal_form, validate: true, html: { class: 'form-horizontal' }) do |f| %>
   <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 .col-lg-offset-4 col-md-offset-4">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :profile_picture %>
    <%= f.input :banner_picture %>
    <%= f.input :bio %>
  </div>

  <div align="center" class="col-lg-4 col-md-4 col-sm-12 col-xs-12 .col-lg-offset-4 col-md-offset-4">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/_profiles.html.erb
<% profiles.each do |profile| %>
  <div class="media">
    <a class="media-left media-middle" href=<%= profile_path(profile) %> >
      <img id="profile-picture" class="media-object" src="<%= profile.profile_picture %>">
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= "#{profile.firstname} #{profile.lastname}" %></h4>
      <%= profile.bio %>
    </div>
  </div>
<% end %>
<%= will_paginate profiles %>

app/views/profiles/edit.html.erb
<div align="center">
  <h1>Editing Profile</h1>
  <%= link_to 'Show', @profile %> |
  <%= link_to 'Back', :back %>
</div>

<%= render 'form' %>

app/views/profiles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
      <%= form_tag profiles_path, method: 'get', id: "profiles_search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class:"form-control" %>
          <%= submit_tag "Search", name: nil, class:"btn btn-primary"  %>
        </p>
      <% end %>
      <%= render partial: "profiles", locals: { profiles: @profiles } %>
    </div>
  </div>
</div>

app/views/profiles/index.js.erb
$("#profiles").html("<%= escape_javascript(render("profiles")) %>");

app/views/profiles/new.html.erb
<div align="center">
  <h1>New Profile</h1>
  <%= link_to 'Back', :back %>
</div>

<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
  <div id="articles-background">
    <div id="articles" class="transitions-enabled">
      <% @articles.each do |article| %>
        <%= render partial: "articles/article", locals: { article: article } %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
  <%= render partial: "categories/categories", locals: { categories: @categories } %>
</div>

app/views/profiles/show.js.erb
$('#articles').html("<%= escape_javascript render(@articles) %>");
$('#articles').masonry('reload');